<AddTaskContent>:
    orientation: "vertical"
    spacing: "12dp"
    padding: "0dp", "40dp", "0dp", "12dp"   # <-- pushes content down
    size_hint_y: None
    height: self.minimum_height

    MDTextField:
        id: task_name
        hint_text: "Task Name"

    MDTextField:
        id: description
        hint_text: "Description"
        multiline: True

    MDTextField:
        id: deadline
        hint_text: "Deadline (optional)"
        readonly: True

    MDTextField:
        id: category
        hint_text: "Category"


<EditTaskContent>:
    orientation: "vertical"
    spacing: "12dp"
    padding: "12dp"
    size_hint_y: None
    height: self.minimum_height

    MDTextField:
        id: task_name
        hint_text: "Task Name"

    MDTextField:
        id: description
        hint_text: "Description"
        multiline: True

    MDTextField:
        id: deadline
        hint_text: "Deadline (optional)"
        readonly: True

    MDTextField:
        id: category
        hint_text: "Category"
