<AddTaskContent>:
    orientation: "vertical"
    spacing: "12dp"
    padding: "12dp"
    size_hint_y: None
    height: self.minimum_height

    MDTextField:
        id: task_name
        hint_text: "Task Name"
        size_hint_y: None
        height: "48dp"

    MDTextField:
        id: description
        hint_text: "Description (Optional)"
        size_hint_y: None
        height: "120dp"
        multiline: True

    MDTextField:
        id: deadline
        hint_text: "Deadline (optional)"
        readonly: True
        size_hint_y: None
        height: "48dp"
        on_focus:
            if self.focus: app.root.ids.main_window.open_deadline_for_field(self)

    MDBoxLayout:
        orientation: "horizontal"
        spacing: "8dp"
        size_hint_y: None
        height: "48dp"

        MDTextField:
            id: category
            hint_text: "Category"
            readonly: True
            size_hint_x: 1

        MDRaisedButton:
            text: "▼"
            size_hint_x: None
            width: "48dp"
            on_release:
                app.root.ids.main_window.category_menu.open()

        MDRaisedButton:
            text: "+"
            size_hint_x: None
            width: "48dp"
            on_release:
                app.root.ids.main_window.open_category_creator(source="add_task")


<EditTaskContent>:
    orientation: "vertical"
    spacing: "12dp"
    padding: "12dp"
    size_hint_y: None
    height: self.minimum_height

    MDTextField:
        id: task_name
        hint_text: "Task Name"
        size_hint_y: None
        height: "48dp"

    MDTextField:
        id: description
        hint_text: "Description (Optional)"
        size_hint_y: None
        height: "120dp"
        multiline: True

    MDTextField:
        id: deadline
        hint_text: "Deadline (optional)"
        readonly: True
        size_hint_y: None
        height: "48dp"
        on_focus:
            if self.focus: app.root.ids.main_window.open_deadline_for_field(self)

    MDBoxLayout:
        orientation: "horizontal"
        spacing: "8dp"
        size_hint_y: None
        height: "48dp"

        MDTextField:
            id: category
            hint_text: "Category"
            readonly: True
            size_hint_x: 1

        MDRaisedButton:
            text: "▼"
            size_hint_x: None
            width: "48dp"
            on_release:
                app.root.ids.main_window.edit_category_menu.open()

        MDRaisedButton:
            text: "+"
            size_hint_x: None
            width: "48dp"
            on_release:
                app.root.ids.main_window.open_category_creator(source="edit_task")
