<InputFrame>:
    spacing: 0
    padding: 0
    height: "150dp"
    size_hint: 1, None

    # Column 1 — stack Task Name + Description
    MDBoxLayout:
        orientation: "vertical"
        size_hint_x: 1
        spacing: 0
        padding: 0

        MDTextField:
            id: task_name
            mode: "fill"
            hint_text: "Task Name"
            multiline: False
            height: "48dp"
            spacing: 0
            padding: 0

        MDTextField:
            id: description
            mode: "rectangle"
            hint_text: "Description"
            multiline: True
            size_hint_y: 1
            height: "48dp"
            spacing: 0
            padding: 0

    # Column 2 — Add button centered vertically
    MDBoxLayout:

        size_hint: 0.20, 1

        YellowButton:
            text: "+"
            size_hint: 1, 1
            font_size: "30sp"
            on_release: root.add_task()
