<TaskItem>:
    orientation: "horizontal"
    size_hint: 0.33, None
    height: "200dp"
    spacing: "6dp"
    padding: "8dp"

    # --- Left side: card ---
    MDCard:
        radius: [20, 20, 20, 20]
        md_bg_color: 0.2, 0.6, 0.8, 1
        padding: "12dp"
        size_hint: 1, 1

        MDBoxLayout:
            orientation: "vertical"
            spacing: "6dp"
            size_hint_y: 1

            MDLabel:
                text: root.task_name
                font_size: "20sp"
                size_hint_y: None
                height: self.texture_size[1]
                halign: "center"
                size_hint: 1, 1

            MDLabel:
                text: root.description
                font_size: "15sp"
                size_hint_y: None
                height: self.texture_size[1]

            MDLabel:
                text: root.deadline
                font_size: "12sp"
                italic: True
                size_hint_y: None
                height: self.texture_size[1]
                halign: "right"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 0.8 


    # --- Right side: buttons ---
    MDBoxLayout:
        orientation: "vertical"
        size_hint: None, 1
        width: "80dp"
        spacing: "6dp"

        YellowButton:
            text: "Done"
            color: 0, 0, 0, 1    
            font_size: "16sp"       
            disabled: root.done
            on_release: root.mark_done()

        YellowButton:
            text: "-"
            color: 0, 0, 0, 1       
            font_size: "25sp"
            on_release: root.remove()

        YellowButton:
            text: "Edit"
            color: 0, 0, 0, 1        
            font_size: "16sp"
            on_release: root.edit_task()